In [3]:
import numpy as np
import pandas as pd

import numpy as np   # import numpy for later use in this tutorial.
import matplotlib.pyplot as plt

pd.__version__

'0.23.0'

Pandas objects: Pandas objects can be thought of as enhanced versions of NumPy structured array in which rows and columns are identified with labels rather than simple integer indices.

Three fundamental Pandas data structures: the Series, DataFrame, and Index.

<h2>The Pandas Series Object</h2>
A Pandas Series is a one-dimensional array of indexed data. It can be created from a list or array.

In [4]:
data = pd.Series([1,0.5,0.25,0.125])
data

0    1.000
1    0.500
2    0.250
3    0.125
dtype: float64

In [5]:
print(data.values)
print(data.index)

[1.    0.5   0.25  0.125]
RangeIndex(start=0, stop=4, step=1)


In [6]:
# accessing the value-using index 
data[1]

0.5

In [7]:
#data[5]   # it will give an error because index 5 is not present in the data.

In [8]:
data[1:3] #index starts from zero. Here values for index 1 and index 2 are selected. Note that end index is not inclusive while selecting values.

1    0.50
2    0.25
dtype: float64

In [9]:
# Data can be scalar, which is repeated to fill the specified index.
pd.Series(5, index=[100,200,300])

100    5
200    5
300    5
dtype: int64

In [10]:
#pd.Series([5,6], index=[100,200,300]) # it will give and error because length of passed values is not same as no. of indices.

In [11]:
# Series creation using dictionary:
pd.Series({2:'a',1:'b',3:'c'})


2    a
1    b
3    c
dtype: object

In [12]:
# Index can be explicitly set if different result is preferred.
pd.Series({2:'a',1:'b',3:'c'}, index=[3,2])

3    c
2    a
dtype: object

<h2>The Pandas DataFrame Object</h2>

DataFrame is an analog of a two-dimensional array with both flexible row indices and flexible column names.

Therefore, we can them as generalization of a NumPy array or as a specialization of a Python dictionary.

In [13]:
# Let's create two dictionary objects:
population_dict = {'California': 38332521,
'Texas': 26448193,
'New York': 19651127,
'Florida': 19552860,
'Illinois': 12882135}

area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
'Florida': 170312, 'Illinois': 149995}

In [14]:
# Now let's create series objects from dictionaries:

area = pd.Series(area_dict)
population = pd.Series(population_dict)

#area
#population

In [15]:
# We can now create a DataFrame using both series objects:
states = pd.DataFrame({'population':population, 'area':area})

states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [16]:
print("Indices are:", states.index)
print("Columns are:", states.columns)

Indices are: Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')
Columns are: Index(['population', 'area'], dtype='object')


<h2>Constructing DataFrame objects</h2>

In [17]:
# From a single Series object:

pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [18]:
# From a list of dicts:

data = [{'a': i, 'b': 2*i} for i in range(3)]
data

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

In [19]:
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [20]:
# Even if some keys in the dictionary are missing, Pandas will fill them in with NaN (i.e.,
#“not a number”) values:

pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [21]:
# From a dictionary of Series objects

pd.DataFrame({'population':population,
             'area':area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [22]:
# From a two-dimensional NumPy array

pd.DataFrame(np.random.rand(3,2),
            columns = ['x','y'],
            index= ['a','b','c'])

x         y
a  0.277985  0.166581
b  0.668628  0.607494
c  0.305186  0.936023

In [23]:
# From a NumPy structure array
A = np.zeros(3, dtype=[('A','i8'),('B','f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [24]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

In [25]:
#pd.Index?

In [26]:
ind = pd.Index([2,3,4,13,5,7,11])
ind

Int64Index([2, 3, 4, 13, 5, 7, 11], dtype='int64')

In [27]:
print(ind[1])
print(ind[::2])

3
Int64Index([2, 4, 5, 11], dtype='int64')


In [28]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

7 (7,) 1 int64


In [29]:
# Note: Index objects are immutable while NumPy arrays are mutable.
# ind[1] = 0    # it will give an error: TypeError: Index does not support mutable operations

In [30]:
indA = pd.Index([1,3,5,7,9])
indB = pd.Index([2,3,5,7,11])

In [31]:
indA & indB            #intersection

Int64Index([3, 5, 7], dtype='int64')

In [32]:
indA | indB           #union

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [33]:
indA ^ indB           #symmetric difference


Int64Index([1, 2, 9, 11], dtype='int64')

In [34]:
# Other way to get above results through object methods:
indA.intersection(indB)

Int64Index([3, 5, 7], dtype='int64')

<h2>Selection</h2>

In [35]:
sample_numpy_data = np.array(np.arange(24)).reshape((6,4))
sample_numpy_data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [36]:
dates_index = pd.date_range('20160101', periods=6)
dates_index

DatetimeIndex(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
               '2016-01-05', '2016-01-06'],
              dtype='datetime64[ns]', freq='D')

In [37]:
sample_df = pd.DataFrame(sample_numpy_data, index= dates_index, columns=list('ABCD'))
sample_df

A   B   C   D
2016-01-01   0   1   2   3
2016-01-02   4   5   6   7
2016-01-03   8   9  10  11
2016-01-04  12  13  14  15
2016-01-05  16  17  18  19
2016-01-06  20  21  22  23

<h5>Selection using column name</h5>

In [38]:
sample_df['C']

2016-01-01     2
2016-01-02     6
2016-01-03    10
2016-01-04    14
2016-01-05    18
2016-01-06    22
Freq: D, Name: C, dtype: int32

<h5>Selection using slice</h5>

- note: last index is not included

In [39]:
sample_df[1:4]          

A   B   C   D
2016-01-02   4   5   6   7
2016-01-03   8   9  10  11
2016-01-04  12  13  14  15

<h5>Selection using date time index</h5>
- note: last index is included

In [40]:
sample_df['2016-01-01':'2016-01-04']

A   B   C   D
2016-01-01   0   1   2   3
2016-01-02   4   5   6   7
2016-01-03   8   9  10  11
2016-01-04  12  13  14  15

<h2>Selection by label</h2>

label-location based indexer for selection by label

In [41]:
sample_df.loc[dates_index[1:3]]

A  B   C   D
2016-01-02  4  5   6   7
2016-01-03  8  9  10  11

<h5>Selecting using multi-axis by label</h5>

In [42]:
sample_df.loc[:, ['A','B']]

A   B
2016-01-01   0   1
2016-01-02   4   5
2016-01-03   8   9
2016-01-04  12  13
2016-01-05  16  17
2016-01-06  20  21

<h5>Label slicing, both endpoints are included</h5>

In [43]:
sample_df.loc['2016-01-01':'2016-01-03', ['A','B']]

A  B
2016-01-01  0  1
2016-01-02  4  5
2016-01-03  8  9

<h5>Reduce number of dimensions for returned object
- notice order of 'D' and 'B'

In [44]:
sample_df.loc['2016-01-03', ['D', 'B']]

D    11
B     9
Name: 2016-01-03 00:00:00, dtype: int32

In [45]:
sample_df.loc['2016-01-03', ['D', 'B']][0] * 4

44

<h5>Select a scalar</h5>

In [46]:
sample_df.loc[dates_index[2],'C']

10

<h2>Selection by Position</h2>
integer-location based indexing for selection by position

In [47]:
sample_df

A   B   C   D
2016-01-01   0   1   2   3
2016-01-02   4   5   6   7
2016-01-03   8   9  10  11
2016-01-04  12  13  14  15
2016-01-05  16  17  18  19
2016-01-06  20  21  22  23

In [48]:
sample_numpy_data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [49]:
sample_numpy_data[3]

array([12, 13, 14, 15])

In [50]:
sample_df.iloc[3]

A    12
B    13
C    14
D    15
Name: 2016-01-04 00:00:00, dtype: int32

<h5>integer slices</h5>

In [51]:
sample_df.iloc[1:3, 2:4]        #two rows, two columns, last index value not included in each case.

C   D
2016-01-02   6   7
2016-01-03  10  11

In [52]:
#Note:
sample_df.iloc[1:13, 2:10]  #note that indices 13,10 are not available in rows and columns, but it doesn't 
#throw any error. from first position to last index available, values are selected. 

C   D
2016-01-02   6   7
2016-01-03  10  11
2016-01-04  14  15
2016-01-05  18  19
2016-01-06  22  23

<h5>list of integers</h5>

In [53]:
sample_df.iloc[[0,1,3],[0,2]] #select first(index 0), second(index 1) and fourth(index 3) rows and first(index 0) and third(index 2) columns. 

A   C
2016-01-01   0   2
2016-01-02   4   6
2016-01-04  12  14

<h5>slicing rows explicitly</h5>
implicitly selecting all columns

In [54]:
sample_df.iloc[1:3,:]

A  B   C   D
2016-01-02  4  5   6   7
2016-01-03  8  9  10  11

<h5>slicing columns explicitly</h5>
implicitly selecting all rows

In [55]:
sample_df.iloc[:, 1:3]

B   C
2016-01-01   1   2
2016-01-02   5   6
2016-01-03   9  10
2016-01-04  13  14
2016-01-05  17  18
2016-01-06  21  22

### NumPy Universal Functions

If the data within a DataFrame are numeric, NumPy's universal functions can be used on/with the DataFrame.

In [88]:
df = pd.DataFrame(np.random.randn(10, 4), columns=['A', 'B', 'C', 'D'])
df2 = pd.DataFrame(np.random.randn(7, 3), columns=['A', 'B', 'C'])
sum_df = df + df2
sum_df

A     B     C   D
0  6.05e-01 -1.75 -0.07 NaN
1  9.58e-01 -0.91  1.82 NaN
2 -7.69e-01  2.53  0.79 NaN
3 -1.25e+00 -0.05  1.30 NaN
4 -1.45e-01 -1.17 -0.99 NaN
5 -2.80e+00 -1.35 -3.73 NaN
6 -4.85e-03  1.56  4.43 NaN
7       NaN   NaN   NaN NaN
8       NaN   NaN   NaN NaN
9       NaN   NaN   NaN NaN

##### NaN are handled correctly by universal function

In [89]:
np.exp(sum_df)

A      B      C   D
0  1.83   0.17   0.93 NaN
1  2.61   0.40   6.19 NaN
2  0.46  12.55   2.21 NaN
3  0.29   0.95   3.67 NaN
4  0.86   0.31   0.37 NaN
5  0.06   0.26   0.02 NaN
6  1.00   4.77  84.27 NaN
7   NaN    NaN    NaN NaN
8   NaN    NaN    NaN NaN
9   NaN    NaN    NaN NaN

##### Transpose availabe T attribute

In [90]:
sum_df.T

0     1     2     3     4     5         6   7   8   9
A  0.61  0.96 -0.77 -1.25 -0.15 -2.80 -4.85e-03 NaN NaN NaN
B -1.75 -0.91  2.53 -0.05 -1.17 -1.35  1.56e+00 NaN NaN NaN
C -0.07  1.82  0.79  1.30 -0.99 -3.73  4.43e+00 NaN NaN NaN
D   NaN   NaN   NaN   NaN   NaN   NaN       NaN NaN NaN NaN

In [91]:
np.transpose(sum_df.values)

array([[ 0.60519107,  0.95840566, -0.76908551, -1.24925108, -0.14505773,
        -2.80457432, -0.00484931,         nan,         nan,         nan],
       [-1.74631452, -0.91422316,  2.52961677, -0.05290831, -1.17061639,
        -1.34743389,  1.56325246,         nan,         nan,         nan],
       [-0.07015928,  1.82288116,  0.79183346,  1.29995513, -0.99002731,
        -3.73119446,  4.43408005,         nan,         nan,         nan],
       [        nan,         nan,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan]])

##### dot method on DataFrame implements matrix multiplication
Note: row and column headers

In [93]:
A_df = pd.DataFrame(np.arange(15).reshape((3,5)))
B_df = pd.DataFrame(np.arange(10).reshape((5,2)))
A_df.dot(B_df)

0    1
0   60   70
1  160  195
2  260  320

##### dot method on Series implements dot product

In [94]:
C_Series = pd.Series(np.arange(5,10))
C_Series.dot(C_Series)

255

### dictionary like operations
##### dictionary selection with string index

In [95]:
cookbook_df = pd.DataFrame({'AAA' : [4,5,6,7], 'BBB' : [10,20,30,40],'CCC' : [100,50,-30,-50]})
cookbook_df['BBB']

0    10
1    20
2    30
3    40
Name: BBB, dtype: int64

##### arithmetic vectorized operation using string indices

In [96]:
cookbook_df['BBB'] * cookbook_df['CCC']

0    1000
1    1000
2    -900
3   -2000
dtype: int64

##### column deletion 

In [97]:
del cookbook_df['BBB']
cookbook_df

AAA  CCC
0    4  100
1    5   50
2    6  -30
3    7  -50

In [98]:
last_column = cookbook_df.pop('CCC')
last_column

0    100
1     50
2    -30
3    -50
Name: CCC, dtype: int64

In [99]:
cookbook_df

AAA
0    4
1    5
2    6
3    7

##### add a new column using a Python list

In [100]:
cookbook_df['DDD'] = [32, 21, 43, 'hike']
cookbook_df

AAA   DDD
0    4    32
1    5    21
2    6    43
3    7  hike

##### insert function
documentation: http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.insert.html

In [101]:
cookbook_df.insert(1, "new column", [3,4,5,6])
cookbook_df

AAA  new column   DDD
0    4           3    32
1    5           4    21
2    6           5    43
3    7           6  hike

<h2>Boolean Indexing</h2>
test based upon one column's data

In [56]:
(sample_df['C']) >= 14

#sample_df.C >= 14                #both are equivalent.
#type((sample_df['C']) >= 14)     #pandas.core.series.Series   

2016-01-01    False
2016-01-02    False
2016-01-03    False
2016-01-04     True
2016-01-05     True
2016-01-06     True
Freq: D, Name: C, dtype: bool

In [57]:
(sample_df[['C','A']]) >= 14
#type((sample_df[['C','A']]) >= 14) #pandas.core.frame.DataFrame

C      A
2016-01-01  False  False
2016-01-02  False  False
2016-01-03  False  False
2016-01-04   True  False
2016-01-05   True   True
2016-01-06   True   True

<h5>test based upon entire data set </h5>

In [58]:
sample_df[sample_df >= 11]

A     B     C     D
2016-01-01   NaN   NaN   NaN   NaN
2016-01-02   NaN   NaN   NaN   NaN
2016-01-03   NaN   NaN   NaN  11.0
2016-01-04  12.0  13.0  14.0  15.0
2016-01-05  16.0  17.0  18.0  19.0
2016-01-06  20.0  21.0  22.0  23.0

<h5>isin() method
----------------------------
Returns a boolean Series showing whether each element in the Series is exactly contained in the passed sequence of values.

In [59]:
sample_df_2 = sample_df.copy()
sample_df_2['Fruits'] = ['apple', 'orange','banana','strawberry','blueberry','pineapple']
sample_df_2

A   B   C   D      Fruits
2016-01-01   0   1   2   3       apple
2016-01-02   4   5   6   7      orange
2016-01-03   8   9  10  11      banana
2016-01-04  12  13  14  15  strawberry
2016-01-05  16  17  18  19   blueberry
2016-01-06  20  21  22  23   pineapple

select rows where 'Fruits' column contains either 'banana' or 'pineapple'; notice 'smoothy', which is not in the column

In [60]:
sample_df_2[sample_df_2['Fruits'].isin(['banana','pineapple', 'smoothy'])]

A   B   C   D     Fruits
2016-01-03   8   9  10  11     banana
2016-01-06  20  21  22  23  pineapple

<h2>Assignment Statements</h2>

In [61]:
sample_series = pd.Series([1,2,3,4,5,6], index=pd.date_range('2016-01-01', periods=6))
sample_series

2016-01-01    1
2016-01-02    2
2016-01-03    3
2016-01-04    4
2016-01-05    5
2016-01-06    6
Freq: D, dtype: int64

In [62]:
sample_df_2['Extra Data'] = sample_series*3 + 1
sample_df_2

A   B   C   D      Fruits  Extra Data
2016-01-01   0   1   2   3       apple           4
2016-01-02   4   5   6   7      orange           7
2016-01-03   8   9  10  11      banana          10
2016-01-04  12  13  14  15  strawberry          13
2016-01-05  16  17  18  19   blueberry          16
2016-01-06  20  21  22  23   pineapple          19

<h5>Setting values by label</h5>

In [63]:
sample_df_2.at[dates_index[3], 'Fruits'] = 'pear'
sample_df_2

A   B   C   D     Fruits  Extra Data
2016-01-01   0   1   2   3      apple           4
2016-01-02   4   5   6   7     orange           7
2016-01-03   8   9  10  11     banana          10
2016-01-04  12  13  14  15       pear          13
2016-01-05  16  17  18  19  blueberry          16
2016-01-06  20  21  22  23  pineapple          19

<h5>Setting values by position</h5>

In [64]:
sample_df_2.iat[3,2] = 4444           #assign the value at position (3,2) i.e at intersection of 4th column and 3rd row.
sample_df_2                              

A   B     C   D     Fruits  Extra Data
2016-01-01   0   1     2   3      apple           4
2016-01-02   4   5     6   7     orange           7
2016-01-03   8   9    10  11     banana          10
2016-01-04  12  13  4444  15       pear          13
2016-01-05  16  17    18  19  blueberry          16
2016-01-06  20  21    22  23  pineapple          19

<h5>Setting by assigning with a numpy array</h5>

In [65]:
second_numpy_array = np.array(np.arange(len(sample_df_2))) * 100 + 7
second_numpy_array

array([  7, 107, 207, 307, 407, 507])

In [66]:
sample_df_2['G'] = second_numpy_array
sample_df_2

A   B     C   D     Fruits  Extra Data    G
2016-01-01   0   1     2   3      apple           4    7
2016-01-02   4   5     6   7     orange           7  107
2016-01-03   8   9    10  11     banana          10  207
2016-01-04  12  13  4444  15       pear          13  307
2016-01-05  16  17    18  19  blueberry          16  407
2016-01-06  20  21    22  23  pineapple          19  507

<h2>Missing Data</h2>

pandas uses np.nan to represent missing data.Bye default, n.nan is not included in computations.

nan represents - 'not a number'

In [67]:
browser_index = ['Firefox', 'Chrome', 'Safari', 'IE10', 'Konqueror']

browser_df = pd.DataFrame({
    'http_status': [200,200,404,404,301],
    'response_time': [0.04, 0.02, 0.07, 0.08, 1.0]},
    index = browser_index)
browser_df

http_status  response_time
Firefox            200           0.04
Chrome             200           0.02
Safari             404           0.07
IE10               404           0.08
Konqueror          301           1.00

<h5>reindex() create a copy(not a view)</h5>

In [68]:
new_index= ['Safari', 'Iceweasel', 'Comodo Dragon', 'IE10', 'Chrome']
browser_df_2 = browser_df.reindex(new_index)
browser_df_2

http_status  response_time
Safari               404.0           0.07
Iceweasel              NaN            NaN
Comodo Dragon          NaN            NaN
IE10                 404.0           0.08
Chrome               200.0           0.02

<h5>drop rows that have missing data</h5>

In [69]:
browser_df_3 = browser_df_2.dropna(how='any')
browser_df_3

http_status  response_time
Safari        404.0           0.07
IE10          404.0           0.08
Chrome        200.0           0.02

<h5>fill-in missing data</h5>

In [70]:
browser_df_2.fillna(value=0.001)

http_status  response_time
Safari             404.000          0.070
Iceweasel            0.001          0.001
Comodo Dragon        0.001          0.001
IE10               404.000          0.080
Chrome             200.000          0.020

<h5>get boolean mask where values are nan</h5>

In [71]:
pd.isnull(browser_df_2)

http_status  response_time
Safari               False          False
Iceweasel             True           True
Comodo Dragon         True           True
IE10                 False          False
Chrome               False          False

<h5>NaN propagates during arithmetic operations</h5>

In [72]:
browser_df_2 * 10

http_status  response_time
Safari              4040.0            0.7
Iceweasel              NaN            NaN
Comodo Dragon          NaN            NaN
IE10                4040.0            0.8
Chrome              2000.0            0.2

<h2>Operations</h2>

### descriptive statistics

In [73]:
pd.set_option('display.precision', 2)
sample_df_2.describe()

A      B        C      D  Extra Data       G
count   6.00   6.00     6.00   6.00        6.00    6.00
mean   10.00  11.00   750.33  13.00       11.50  257.00
std     7.48   7.48  1809.53   7.48        5.61  187.08
min     0.00   1.00     2.00   3.00        4.00    7.00
25%     5.00   6.00     7.00   8.00        7.75  132.00
50%    10.00  11.00    14.00  13.00       11.50  257.00
75%    15.00  16.00    21.00  18.00       15.25  382.00
max    20.00  21.00  4444.00  23.00       19.00  507.00

##### column mean

In [74]:
sample_df_2.mean()

A              10.00
B              11.00
C             750.33
D              13.00
Extra Data     11.50
G             257.00
dtype: float64

##### row mean

In [75]:
sample_df_2.mean(1)  # 1 specifies mean value along rows.

2016-01-01      2.83
2016-01-02     22.67
2016-01-03     42.50
2016-01-04    800.67
2016-01-05     82.17
2016-01-06    102.00
Freq: D, dtype: float64

### apply(a function to a data frame)

In [76]:
sample_df_2.apply(np.cumsum) # values are cumulatively added from previous row value to current row value until last row.

A   B     C   D                                   Fruits  \
2016-01-01   0   1     2   3                                    apple   
2016-01-02   4   6     8  10                              appleorange   
2016-01-03  12  15    18  21                        appleorangebanana   
2016-01-04  24  28  4462  36                    appleorangebananapear   
2016-01-05  40  45  4480  55           appleorangebananapearblueberry   
2016-01-06  60  66  4502  78  appleorangebananapearblueberrypineapple   

            Extra Data     G  
2016-01-01           4     7  
2016-01-02          11   114  
2016-01-03          21   321  
2016-01-04          34   628  
2016-01-05          50  1035  
2016-01-06          69  1542

In [77]:
sample_df_2

A   B     C   D     Fruits  Extra Data    G
2016-01-01   0   1     2   3      apple           4    7
2016-01-02   4   5     6   7     orange           7  107
2016-01-03   8   9    10  11     banana          10  207
2016-01-04  12  13  4444  15       pear          13  307
2016-01-05  16  17    18  19  blueberry          16  407
2016-01-06  20  21    22  23  pineapple          19  507

#### string methods

In [78]:
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

In [79]:
s.str.len()

0    1.0
1    1.0
2    1.0
3    4.0
4    4.0
5    NaN
6    4.0
7    3.0
8    3.0
dtype: float64

# Merge
- Concat 
- Join   
- Append 

In [80]:
second_df_2 = sample_df.copy()
sample_df_2['Fruits'] = ['apple', 'orange','banana','strawberry','blueberry','pineapple']

sample_series = pd.Series([1,2,3,4,5,6], index=pd.date_range('2016-01-01', periods=6))
sample_df_2['Extra Data'] = sample_series *3 +1

second_numpy_array = np.array(np.arange(len(sample_df_2)))  *100 + 7
sample_df_2['G'] = second_numpy_array

sample_df_2

A   B     C   D      Fruits  Extra Data    G
2016-01-01   0   1     2   3       apple           4    7
2016-01-02   4   5     6   7      orange           7  107
2016-01-03   8   9    10  11      banana          10  207
2016-01-04  12  13  4444  15  strawberry          13  307
2016-01-05  16  17    18  19   blueberry          16  407
2016-01-06  20  21    22  23   pineapple          19  507

### concat()
##### separate data frame into a list with 3 elements

In [81]:
pieces = [sample_df_2[:2], sample_df_2[2:4], sample_df_2[4:]]
pieces[0]

A  B  C  D  Fruits  Extra Data    G
2016-01-01  0  1  2  3   apple           4    7
2016-01-02  4  5  6  7  orange           7  107

In [82]:
pieces              # list elements

[            A  B  C  D  Fruits  Extra Data    G
 2016-01-01  0  1  2  3   apple           4    7
 2016-01-02  4  5  6  7  orange           7  107,
              A   B     C   D      Fruits  Extra Data    G
 2016-01-03   8   9    10  11      banana          10  207
 2016-01-04  12  13  4444  15  strawberry          13  307,
              A   B   C   D     Fruits  Extra Data    G
 2016-01-05  16  17  18  19  blueberry          16  407
 2016-01-06  20  21  22  23  pineapple          19  507]

##### concatenate first and last elements

In [83]:
new_list = pieces[0], pieces[2]
pd.concat(new_list)

A   B   C   D     Fruits  Extra Data    G
2016-01-01   0   1   2   3      apple           4    7
2016-01-02   4   5   6   7     orange           7  107
2016-01-05  16  17  18  19  blueberry          16  407
2016-01-06  20  21  22  23  pineapple          19  507

### append()

In [84]:
new_last_row = sample_df_2.iloc[2]
new_last_row

A                  8
B                  9
C                 10
D                 11
Fruits        banana
Extra Data        10
G                207
Name: 2016-01-03 00:00:00, dtype: object

In [85]:
sample_df_2.append(new_last_row)

A   B     C   D      Fruits  Extra Data    G
2016-01-01   0   1     2   3       apple           4    7
2016-01-02   4   5     6   7      orange           7  107
2016-01-03   8   9    10  11      banana          10  207
2016-01-04  12  13  4444  15  strawberry          13  307
2016-01-05  16  17    18  19   blueberry          16  407
2016-01-06  20  21    22  23   pineapple          19  507
2016-01-03   8   9    10  11      banana          10  207

### merge()
Merge DataFrame objects by performing a database-style join operation by columns or indexes.

If joining columns on columns, the DataFrame indexes will be ignored. Otherwise if joining indexes on indexes or indexes on a column or columns, the index will be passed on.

In [86]:
left = pd.DataFrame({'my_key': ['K0', 'K1', 'K2', 'K3'],
 'A': ['A0', 'A1', 'A2', 'A3'],
 'B': ['B0', 'B1', 'B2', 'B3']})
right = pd.DataFrame({'my_key': ['K0', 'K1', 'K2', 'K3'],
 'C': ['C0', 'C1', 'C2', 'C3'],
 'D': ['D0', 'D1', 'D2', 'D3']})

left

my_key   A   B
0     K0  A0  B0
1     K1  A1  B1
2     K2  A2  B2
3     K3  A3  B3

In [87]:
result = pd.merge(left, right, on='my_key')
result

my_key   A   B   C   D
0     K0  A0  B0  C0  D0
1     K1  A1  B1  C1  D1
2     K2  A2  B2  C2  D2
3     K3  A3  B3  C3  D3